// Code generated by "stringer -type=ErrCode -output=code_string.go --linecomment"; DO NOT EDIT.

package xerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeSuccess-0]
	_ = x[ErrCodeFail-1]
	_ = x[ErrCodeParamError-400]
	_ = x[ErrCodeUnauthorized-401]
	_ = x[ErrCodeForbidden-403]
	_ = x[ErrCodeNotFound-404]
	_ = x[ErrCodeServerInternalError-500]
	_ = x[ErrCodeServiceUnavailable-503]
	_ = x[ErrCodeUserNotExists-10001]
	_ = x[ErrCodeUserExists-10002]
	_ = x[ErrCodeUserPwdError-10003]
	_ = x[ErrCodeHadBindError-10004]
	_ = x[ErrCodeNotBindError-10005]
	_ = x[ErrCodeRepeatUpdateError-10006]
	_ = x[ErrCodeTemporaryTokenEmptyError-10007]
	_ = x[ErrCodeTemporaryTokenInvalidError-10008]
	_ = x[ErrCodeSelfHadBindError-10009]
	_ = x[ErrCodeBindSameError-10010]
	_ = x[ErrCodeUserAbnormalError-10011]
	_ = x[ErrCodeGoogleAuthError-10012]
	_ = x[ErrCodeGameEnterLogExists-20001]
	_ = x[ErrCodeWithdrawBalanceNotEnough-30001]
	_ = x[ErrCodeWithdrawAmountOutOfRange-30002]
}

const (
	_ErrCode_name_0 = "SuccessFail"
	_ErrCode_name_1 = "ParamErrorUnauthorized"
	_ErrCode_name_2 = "ForbiddenNotFound"
	_ErrCode_name_3 = "ServerInternalError"
	_ErrCode_name_4 = "ServiceUnavailable"
	_ErrCode_name_5 = "UserNotExistsUserExistsUserPwdErrorHadBindErrorNotBindErrorRepeatUpdateErrorTemporaryTokenEmptyErrorTemporaryTokenInvalidErrorSelfHadBindErrorBindSameErrorUserAbnormalErrorGoogleAuthError"
	_ErrCode_name_6 = "GameEnterLogExists"
	_ErrCode_name_7 = "WithdrawBalanceNotEnoughWithdrawAmountOutOfRange"
)

var (
	_ErrCode_index_0 = [...]uint8{0, 7, 11}
	_ErrCode_index_1 = [...]uint8{0, 10, 22}
	_ErrCode_index_2 = [...]uint8{0, 9, 17}
	_ErrCode_index_5 = [...]uint8{0, 13, 23, 35, 47, 59, 76, 100, 126, 142, 155, 172, 187}
	_ErrCode_index_7 = [...]uint8{0, 24, 48}
)

func (i ErrCode) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _ErrCode_name_0[_ErrCode_index_0[i]:_ErrCode_index_0[i+1]]
	case 400 <= i && i <= 401:
		i -= 400
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case 403 <= i && i <= 404:
		i -= 403
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	case i == 500:
		return _ErrCode_name_3
	case i == 503:
		return _ErrCode_name_4
	case 10001 <= i && i <= 10012:
		i -= 10001
		return _ErrCode_name_5[_ErrCode_index_5[i]:_ErrCode_index_5[i+1]]
	case i == 20001:
		return _ErrCode_name_6
	case 30001 <= i && i <= 30002:
		i -= 30001
		return _ErrCode_name_7[_ErrCode_index_7[i]:_ErrCode_index_7[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
