// Code generated by "stringer -type=ErrCode -output=code_string.go --linecomment"; DO NOT EDIT.

package xerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeSuccess-0]
	_ = x[ErrCodeFail-1]
	_ = x[ErrCodeParamError-400]
	_ = x[ErrCodeUnauthorized-401]
	_ = x[ErrCodeForbidden-403]
	_ = x[ErrCodeNotFound-404]
	_ = x[ErrCodeServerInternalError-500]
	_ = x[ErrCodeServiceUnavailable-503]
	_ = x[ErrCodeUserNotExists-10001]
	_ = x[ErrCodeUserExists-10002]
	_ = x[ErrCodeUserPwdError-10003]
	_ = x[ErrCodeHadBindError-10004]
	_ = x[ErrCodeNotBindError-10005]
	_ = x[ErrCodeRepeatUpdateError-10006]
	_ = x[ErrCodeTemporaryTokenEmptyError-10007]
	_ = x[ErrCodeTemporaryTokenInvalidError-10008]
	_ = x[ErrCodeSelfHadBindError-10009]
	_ = x[ErrCodeBindSameError-10010]
	_ = x[ErrCodeUserAbnormalError-10011]
	_ = x[ErrCodeGoogleAuthError-10012]
	_ = x[ErrCodeNicknameTimeError-10013]
	_ = x[ErrCodeMaxNumberError-10014]
	_ = x[ErrCodeBalanceRetrievingError-10015]
	_ = x[ErrCodeNicknameExistError-10016]
	_ = x[ErrCodeOldPasswordError-10017]
	_ = x[ErrCodeLoginLocked-10018]
	_ = x[ErrCodeSetPinLockedFirst-10019]
	_ = x[ErrCodeOldPinError-10020]
	_ = x[ErrCodeSetPinLockedMax-10022]
	_ = x[ErrCodeWithdrawAccountNotExists-10023]
	_ = x[ErrCodeWithdrawAccountNotSetPin-10024]
	_ = x[ErrCodeSetPinCaptchaNumError-10025]
	_ = x[ErrCodeGameEnterLogExists-20001]
	_ = x[ErrCodeGameEnterBalanceNotEnough-20002]
	_ = x[ErrCodeGamePlatformUnreachable-20003]
	_ = x[ErrCodeWithdrawBalanceNotEnough-30001]
	_ = x[ErrCodeWithdrawAmountOutOfRange-30002]
	_ = x[ErrCodeRechargeAmountOutOfChannelDayMax-30003]
	_ = x[ErrCodeWithdrawLocked-30004]
	_ = x[ErrCodePinCheckError-30005]
	_ = x[ErrCodeInvalidPromotionCode-40000]
	_ = x[ErrCodeBindParentNotAllowed-40001]
	_ = x[ErrCodeCaptchaErr-50001]
	_ = x[ErrCodeActivityNotStart-60001]
	_ = x[ErrCodeActivityEnded-60002]
	_ = x[ErrCodeActivityClosed-60003]
	_ = x[ErrCodeRewardNotAvailableYet-60004]
	_ = x[ErrCodeRewardNotBelongToYou-60005]
	_ = x[ErrCodeRewardConditionNotMet-60006]
	_ = x[ErrCodeRewardNotClaimable-60007]
	_ = x[ErrCodeRewardExpired-60008]
}

const _ErrCode_name = "SuccessFailParamErrorUnauthorizedForbiddenNotFoundServerInternalErrorServiceUnavailableUserNotExistsUserExistsUserPwdErrorHadBindErrorNotBindErrorRepeatUpdateErrorTemporaryTokenEmptyErrorTemporaryTokenInvalidErrorSelfHadBindErrorBindSameErrorUserAbnormalErrorGoogleAuthErrorNicknameTimeErrorMaxNumberErrorBalanceRetrievingErrorNicknameExistErrorOldPasswordErrorLoginLockedSetPinLockedFirstOldPinErrorSetPinLockedMaxWithdrawAccountNotExistsWithdrawAccountNotSetPinSetPinCaptchaNumErrorGameEnterLogExistsErrCodeGameEnterLogExistsGamePlatformUnreachableWithdrawBalanceNotEnoughWithdrawAmountOutOfRangeErrCodeRechargeAmountOutOfChannelDayMaxWithdrawLockedPinCheckErrorErrCodeInvalidPromotionCodeErrCodeBindParentNotAllowedErrCodeCaptchaErrErrCodeActivityNotStartErrCodeActivityEndedErrCodeActivityClosedErrCodeRewardNotAvailableYetErrCodeRewardNotBelongToYouErrCodeRewardConditionNotMetErrCodeRewardNotClaimableErrCodeRewardExpired"

var _ErrCode_map = map[ErrCode]string{
	0:     _ErrCode_name[0:7],
	1:     _ErrCode_name[7:11],
	400:   _ErrCode_name[11:21],
	401:   _ErrCode_name[21:33],
	403:   _ErrCode_name[33:42],
	404:   _ErrCode_name[42:50],
	500:   _ErrCode_name[50:69],
	503:   _ErrCode_name[69:87],
	10001: _ErrCode_name[87:100],
	10002: _ErrCode_name[100:110],
	10003: _ErrCode_name[110:122],
	10004: _ErrCode_name[122:134],
	10005: _ErrCode_name[134:146],
	10006: _ErrCode_name[146:163],
	10007: _ErrCode_name[163:187],
	10008: _ErrCode_name[187:213],
	10009: _ErrCode_name[213:229],
	10010: _ErrCode_name[229:242],
	10011: _ErrCode_name[242:259],
	10012: _ErrCode_name[259:274],
	10013: _ErrCode_name[274:291],
	10014: _ErrCode_name[291:305],
	10015: _ErrCode_name[305:327],
	10016: _ErrCode_name[327:345],
	10017: _ErrCode_name[345:361],
	10018: _ErrCode_name[361:372],
	10019: _ErrCode_name[372:389],
	10020: _ErrCode_name[389:400],
	10022: _ErrCode_name[400:415],
	10023: _ErrCode_name[415:439],
	10024: _ErrCode_name[439:463],
	10025: _ErrCode_name[463:484],
	20001: _ErrCode_name[484:502],
	20002: _ErrCode_name[502:527],
	20003: _ErrCode_name[527:550],
	30001: _ErrCode_name[550:574],
	30002: _ErrCode_name[574:598],
	30003: _ErrCode_name[598:637],
	30004: _ErrCode_name[637:651],
	30005: _ErrCode_name[651:664],
	40000: _ErrCode_name[664:691],
	40001: _ErrCode_name[691:718],
	50001: _ErrCode_name[718:735],
	60001: _ErrCode_name[735:758],
	60002: _ErrCode_name[758:778],
	60003: _ErrCode_name[778:799],
	60004: _ErrCode_name[799:827],
	60005: _ErrCode_name[827:854],
	60006: _ErrCode_name[854:882],
	60007: _ErrCode_name[882:907],
	60008: _ErrCode_name[907:927],
}

func (i ErrCode) String() string {
	if str, ok := _ErrCode_map[i]; ok {
		return str
	}
	return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
