// Code generated by "stringer -type=ErrCode -output=code_string.go --linecomment"; DO NOT EDIT.

package xerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrCodeSuccess-0]
	_ = x[ErrCodeFail-1]
	_ = x[ErrCodeParamError-400]
	_ = x[ErrCodeUnauthorized-401]
	_ = x[ErrCodeForbidden-403]
	_ = x[ErrCodeNotFound-404]
	_ = x[ErrCodeServerInternalError-500]
	_ = x[ErrCodeServiceUnavailable-503]
	_ = x[ErrCodeUserNotExists-10001]
	_ = x[ErrCodeUserExists-10002]
	_ = x[ErrCodeUserPwdError-10003]
	_ = x[ErrCodeHadBindError-10004]
	_ = x[ErrCodeNotBindError-10005]
	_ = x[ErrCodeRepeatUpdateError-10006]
	_ = x[ErrCodeTemporaryTokenEmptyError-10007]
	_ = x[ErrCodeTemporaryTokenInvalidError-10008]
	_ = x[ErrCodeSelfHadBindError-10009]
	_ = x[ErrCodeBindSameError-10010]
	_ = x[ErrCodeUserAbnormalError-10011]
	_ = x[ErrCodeThirdPartyAuthError-10012]
	_ = x[ErrCodeNicknameTimeError-10013]
	_ = x[ErrCodeMaxNumberError-10014]
	_ = x[ErrCodeBalanceRetrievingError-10015]
	_ = x[ErrCodeNicknameExistError-10016]
	_ = x[ErrCodeOldPasswordError-10017]
	_ = x[ErrCodeLoginLocked-10018]
	_ = x[ErrCodeSetPinLockedFirst-10019]
	_ = x[ErrCodeOldPinError-10020]
	_ = x[ErrCodeSetPinLockedMax-10022]
	_ = x[ErrCodeWithdrawAccountNotExists-10023]
	_ = x[ErrCodeWithdrawAccountNotSetPin-10024]
	_ = x[ErrCodeSetPinCaptchaNumError-10025]
	_ = x[ErrCodeUserStatusForbidden-10026]
	_ = x[ErrCodeGameEnterLogExists-20001]
	_ = x[ErrCodeGameEnterBalanceNotEnough-20002]
	_ = x[ErrCodeGamePlatformUnreachable-20003]
	_ = x[ErrCodeWithdrawBalanceNotEnough-30001]
	_ = x[ErrCodeWithdrawAmountOutOfRange-30002]
	_ = x[ErrCodeRechargeAmountOutOfChannelDayMax-30003]
	_ = x[ErrCodeWithdrawLocked-30004]
	_ = x[ErrCodeWithdrawPinCheckError-30005]
	_ = x[ErrCodeUserWithdrawForbidden-30006]
	_ = x[ErrCodeWithdrawLockedFirst-30007]
	_ = x[ErrCodeInvalidPromotionCode-40000]
	_ = x[ErrCodeBindParentNotAllowed-40001]
	_ = x[ErrCodeCaptchaErr-50001]
	_ = x[ErrCodeActivityNotStart-60001]
	_ = x[ErrCodeActivityEnded-60002]
	_ = x[ErrCodeActivityClosed-60003]
	_ = x[ErrCodeRewardNotAvailableYet-60004]
	_ = x[ErrCodeRewardNotBelongToYou-60005]
	_ = x[ErrCodeRewardConditionNotMet-60006]
	_ = x[ErrCodeRewardNotClaimable-60007]
	_ = x[ErrCodeRewardExpired-60008]
}

const _ErrCode_name = "SuccessFailParamErrorUnauthorizedForbiddenNotFoundServerInternalErrorServiceUnavailableUserNotExistsUserExistsUserPwdErrorHadBindErrorNotBindErrorRepeatUpdateErrorTemporaryTokenEmptyErrorTemporaryTokenInvalidErrorSelfHadBindErrorBindSameErrorUserAbnormalErrorThirdPartyAuthErrorNicknameTimeErrorMaxNumberErrorBalanceRetrievingErrorNicknameExistErrorOldPasswordErrorLoginLockedSetPinLockedFirstOldPinErrorSetPinLockedMaxWithdrawAccountNotExistsWithdrawAccountNotSetPinSetPinCaptchaNumErrorUserStatusForbiddenGameEnterLogExistsErrCodeGameEnterLogExistsGamePlatformUnreachableWithdrawBalanceNotEnoughWithdrawAmountOutOfRangeRechargeAmountOutOfChannelDayMaxWithdrawLockedWithdrawPinCheckErrorUserWithdrawForbiddenWithdrawLockedFirstErrCodeInvalidPromotionCodeErrCodeBindParentNotAllowedErrCodeCaptchaErrErrCodeActivityNotStartErrCodeActivityEndedErrCodeActivityClosedErrCodeRewardNotAvailableYetErrCodeRewardNotBelongToYouErrCodeRewardConditionNotMetErrCodeRewardNotClaimableErrCodeRewardExpired"

var _ErrCode_map = map[ErrCode]string{
	0:     _ErrCode_name[0:7],
	1:     _ErrCode_name[7:11],
	400:   _ErrCode_name[11:21],
	401:   _ErrCode_name[21:33],
	403:   _ErrCode_name[33:42],
	404:   _ErrCode_name[42:50],
	500:   _ErrCode_name[50:69],
	503:   _ErrCode_name[69:87],
	10001: _ErrCode_name[87:100],
	10002: _ErrCode_name[100:110],
	10003: _ErrCode_name[110:122],
	10004: _ErrCode_name[122:134],
	10005: _ErrCode_name[134:146],
	10006: _ErrCode_name[146:163],
	10007: _ErrCode_name[163:187],
	10008: _ErrCode_name[187:213],
	10009: _ErrCode_name[213:229],
	10010: _ErrCode_name[229:242],
	10011: _ErrCode_name[242:259],
	10012: _ErrCode_name[259:278],
	10013: _ErrCode_name[278:295],
	10014: _ErrCode_name[295:309],
	10015: _ErrCode_name[309:331],
	10016: _ErrCode_name[331:349],
	10017: _ErrCode_name[349:365],
	10018: _ErrCode_name[365:376],
	10019: _ErrCode_name[376:393],
	10020: _ErrCode_name[393:404],
	10022: _ErrCode_name[404:419],
	10023: _ErrCode_name[419:443],
	10024: _ErrCode_name[443:467],
	10025: _ErrCode_name[467:488],
	10026: _ErrCode_name[488:507],
	20001: _ErrCode_name[507:525],
	20002: _ErrCode_name[525:550],
	20003: _ErrCode_name[550:573],
	30001: _ErrCode_name[573:597],
	30002: _ErrCode_name[597:621],
	30003: _ErrCode_name[621:653],
	30004: _ErrCode_name[653:667],
	30005: _ErrCode_name[667:688],
	30006: _ErrCode_name[688:709],
	30007: _ErrCode_name[709:728],
	40000: _ErrCode_name[728:755],
	40001: _ErrCode_name[755:782],
	50001: _ErrCode_name[782:799],
	60001: _ErrCode_name[799:822],
	60002: _ErrCode_name[822:842],
	60003: _ErrCode_name[842:863],
	60004: _ErrCode_name[863:891],
	60005: _ErrCode_name[891:918],
	60006: _ErrCode_name[918:946],
	60007: _ErrCode_name[946:971],
	60008: _ErrCode_name[971:991],
}

func (i ErrCode) String() string {
	if str, ok := _ErrCode_map[i]; ok {
		return str
	}
	return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
